/*******************************************************************************
*****************                IDENTIY     ***********************************
********************************************************************************/

-- PostgreSQL version 10 a introduit une nouvelle fonctionnalité appelée GENERATED AS IDENTITY
-- contrainte qui vous permet d'attribuer automatiquement une valeur unique à une colonne.

-- Le type peut être SMALLINT, INT ou BIGINT.
-- Le GENERATED ALWAYS demande à PostgreSQL de toujours générer une valeur pour la colonne d'identité.
-- Si vous essayez d' insérer (ou de mettre à jour ) une valeur dans la colonne GENERATED ALWAYS AS IDENTITY, PostgreSQL générera une erreur.

--- Creation de la table 

CREATE TABLE couleur (
    color_id INT GENERATED ALWAYS AS IDENTITY,
    coleur_name VARCHAR NOT NULL
);

-- Insertion d'une valeur  :

INSERT INTO couleur (coleur_name)
VALUES ('Rouge')

-- et le SELECT 

select * from couleur

-- PostgreSQL génère une valeur pour elle comme indiqué dans la requête ci-dessous:

-- Et si on essaye d'inserer une valeur en dur ? 

INSERT INTO couleur (color_id, coleur_name)
VALUES
    (2, 'Green')
	
--Cela ne fonctionne pas, on demande OVERRIDING SYSTEM VALUE

INSERT INTO couleur (color_id, coleur_name)
OVERRIDING SYSTEM VALUE 
VALUES
    (2, 'Green')
	
-- et le SELECT 

select * from couleur

-- Il y a aussi GENERATED BY DEFAULT AS IDENTITY :

-- Suppression et recreation de la table 

DROP TABLE couleur;
 
CREATE TABLE couleur (
    color_id INT GENERATED BY DEFAULT AS IDENTITY,
    color_name VARCHAR NOT NULL
);

-- Insertion de valeur 
INSERT INTO couleur (color_name)
VALUES
    ('White')
	
-- et le SELECT 

select * from couleur	

-- cela fonctionne, et si on force une valeur ? 


INSERT INTO couleur (color_id, color_name)
VALUES
    (2, 'Green')
	
-- et le SELECT 

select * from couleur	

-- Il prend la valeur meme si l'on force l'insertion

-- On peut modifier aussi le pas d'increment

DROP TABLE couleur;
 
CREATE TABLE color (
    color_id INT GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 10 INCREMENT BY 10),-- demarre a 10 et fais un saut a 10
    color_name VARCHAR NOT NULL
); 
	
INSERT INTO color (color_name)
VALUES
    ('Orange');	
	
select * from color	

-- L'increment part a 10 

-- Et si j'insere une nouvelle valeur 

INSERT INTO color (color_name)
VALUES
    ('Purple')
	
-- La on va a 20


	